version: "3.8"

services:
  app:
    build: .
    container_name: mychatbot
    ports:
      - "3001:3001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    stdin_open: true
    tty: true
